spring:
  application:
    name: DNA2ProteinTranslator
  datasource:
    url: jdbc:mysql://localhost:3306/dna2protein
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate